name: 'Lock Closed Threads'

on:
  schedule:
    - cron: '0 7 * * *'  # 7am UTC, daily
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    if: github.repository_owner == 'pypa'
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@be8aa5be94131386884a6da4189effda9b14aa21 # v4.0.1
        with:
          issue-inactive-days: '30'
          pr-inactive-days: '15'
